weigths: 
- 0.0E-12 #acceleration
- 0         #Effort
- 1.0E-2 #scaling   
- 1.0E+3 #position
- 0   #jerk

nax             : 3
nc              : 5
control_horizon : 0.01
st              : 0.001

qmax            : 10
qmin            : -10
Dqmax           : 10
DDqmax          : 50
tau_max         : 100

spline_order    : 3