# Nome del workflow
name: 'colcon Build Check (ROS-Free)'

# Trigger: si avvia su push o pull request a 'main'
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-ros-free:
    # 1. Ambiente: Ubuntu pulito (senza Docker o ROS)
    runs-on: ubuntu-latest

    # 2. Elenco dei passaggi
    steps:
      # 2.1. Scarica il codice del repository
      # Questo ci porta già all'interno della cartella 'thor_trajectory_lib'
      - name: Check out repository
        uses: actions/checkout@v4

     # 2.2. Installa TUTTE le dipendenze
      - name: Install All Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            build-essential \
            cmake \
            git \
            python3-pip \
            pkg-config \
            libeigen3-dev \
            libboost-all-dev \
            libyaml-cpp-dev \
            libpoco-dev \
            liblog4cxx-dev \
            libgtest-dev

          python3 -m pip install --upgrade pip
          # colcon "ROS-free"
          python3 -m pip install colcon-common-extensions

      # 2.3. Rende eseguibile lo script
      - name: Make script executable
        run: chmod +x setup_thor_ws.sh

      # 2.4. Esegue lo script di setup e build
      # Lo script si occuperà di installare build-essential, CMake, Eigen
      # e poi eseguirà colcon build
      - name: Run setup_thor_ws.sh
        run: bash setup_thor_ws.sh -j 8 -b Release --install-deps