# Nome del workflow
name: 'colcon Build Check'

# Trigger: si avvia su push o pull request a 'main'
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-ros:
    # 1. Definiamo l'ambiente (es. ROS 2 Humble)
    # Cambia 'humble' se usi un'altra versione (es. iron, rolling)
    runs-on: ubuntu-latest
    container:
      image: ros:humble-ros-base

    # 2. Elenco dei passaggi
    steps:
      # 2.1. Scarica il codice del repository
      # Questo ci porta già all'interno della cartella 'thor_trajectory_lib'
      - name: Check out repository
        uses: actions/checkout@v4

      # 2.2. (Opzionale ma consigliato) Aggiorna apt
      # Utile prima di eseguire uno script che installa dipendenze
      - name: Update apt
        run: sudo apt-get update

      # 2.3. Rende eseguibile lo script (se non lo è già)
      # Assumendo che 'setup_thor_ws.sh' sia nella root del repo
      - name: Make script executable
        run: chmod +x setup_thor_ws.sh

      # 2.4. Esegue lo script di setup e build
      # Usiamo i flag che hai specificato
      - name: Run setup_thor_ws.sh
        run: bash setup_thor_ws.sh -j 8 -b Release --install-deps